site_name: Duktig PHP Microservice
site_description: Duktig PHP Microservice - Development documentation
site_author: Davit A. <david@duktig.solutions>
copyright: Copyright &copy; 2023 <a href='https://duktig.solutions'>Duktig Solutions LLC</a>
extra_css: [css/duktig.css]

hide:
  - toc

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    - primary: default
  features:
#    - navigation.path
    - toc.integrate
    - navigation.tracking
#    - navigation.sections
    - navigation.expand
#    - navigation.top
    - content.code.copy
    - navigation.footer

#  custom_dir: _doc_build_custom_theme

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
#      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:
  generator: false
  homepage: https://duktig.solutions
  site_url: https://duktig.solutions
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/duktig-solutions
      name: Duktig Solutions on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DuktigS
      name: Duktig Solutions on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/duktig-solutions
      name: Duktig Solutions on LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:support@duktig.solutions
      name: Send an Email to Duktig Solutions
    - icon: fontawesome/solid/home
      link: https://duktig.solutions
      name: Duktig Solutions LLC - Home page


#plugins:
#  - search:
#      indexing: 'full'

nav:
    - Overview:
        - index.md
        - overview/requirements.md
        - overview/change-log.md
#   - Installation:
#       - installation/env-configuration.md
#       - installation/local-dev-deployment.md
#   - Development:
#       - development/config.md
#       - development/environment.md
#       - development/routing.md
#       - development/http.md
#       - development/cli.md
#       - development/middleware.md
#       - development/controller.md
#       - development/model.md
#       - development/lib.md
#       - development/worker.md
#       - development/error-handling.md
#       - development/logging.md
#       - development/events-pub-sub.md
#       - development/message-queue.md
#   - Libraries:
#       - libs/auth/jwt.md
#       - libs/auth/password.md
#       - libs/cache/redis.md
#       - libs/db/mysql.md
#       - libs/db/mysql-utility.md
#       - libs/db/postgresql.md
#       - libs/events/event.md
#       - libs/events/event-publisher.md
#       - libs/http/client-info.md
#       - libs/http/client.md
#       - libs/benchmarking.md
#       - libs/date.md
#       - libs/generator.md
#       - libs/location-by-ip.md
#       - libs/valid.md
#       - libs/validator.md
#   - Code examples:
#       - examples/cli.md
#       - examples/validation.md
#       - examples/message-queue.md
#       - examples/pub-sub.md
#       - examples/benchmarking.md
#       - examples/caching.md
#   - Tutorials:
#       - tutorials/crud-development.md
#       - tutorials/pub-sub.md
#       - tutorials/message-queue.md
#       - tutorials/db-backup.md
    - References:
#       - references/predefined-constants.md
        - references/coding-standards.md
#   - faq.md
#   - todo.md